/**
 * Generate browser-safe embedded schema constants from repo schemas/.
 *
 * Run from repo root: node packages/typescript/spec/scripts/embed-schemas.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../../../../");
const schemasDir = path.join(repoRoot, "schemas");
const outPath = path.join(here, "../src/embedded_schemas.ts");

const NAMES = [
  "workspace-value",
  "secret-ref",
  "variable",
  "workspace",
  "rule-ast",
  "bit",
  "bit-type-manifest",
  "document-definition",
  "recipe",
  "workspace-patch",
  "compiled-project",
  "run-results",
  "project",
];

const entries = NAMES.map((name) => {
  const filePath = path.join(schemasDir, `${name}.schema.json`);
  const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
  return `  ${JSON.stringify(name)}: ${JSON.stringify(data)} as Record<string, unknown>,`;
});

const source = `/** Auto-generated by scripts/embed-schemas.mjs — do not edit. */

export const EMBEDDED_SCHEMAS: Record<string, Record<string, unknown>> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(outPath, source, "utf8");
console.log("Wrote", outPath, `(${NAMES.length} schemas)`);
